author: "Tom Meagher"
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "base"
description: "Tom Meagher lives in NYC and does tech things."
exclude:
  - ".gitignore"
  - "CNAME"
  - "LICENSE"
  - "README.md"
keywords: "tom, tomfme, meagher, code, design, startups, technology, tech, design, nyc"
permalink: pretty
sass:
  style: compressed
  sass_dir: "assets/styles"
timezone: America/New_York
title: Tom Meagher
url: "https://meagher.co"
